Club portal
teau-ict-club/club-website pull request #23
Opened 2021-11-11 21:10 UTC by Linusmugera

Added menu section modified some features in the body section added some files

2021-11-13 16:05 UTC, Chal13W1zz approved these changes

2021-11-13 18:01 UTC, Chal13W1zz requested changes
Kindly follow the folder structure, firebase won't detect anything outside the public folder.
Place all your images inside "public/img" and maybe you can create sub folders in there according to the respective HTML files where the images are to be displayed,
do the same for the css files, place all your CSS files inside "public/css".

Make sure you also check on the naming convention, if a css file belongs to display.html, it should be named display.css, the same case applies to javascript, if you'll use external javascript files.
For example, if a js file belongs to display.html, name it display.js and place it inside the "pu
blic/js" folder.

For the images, to avoid naming conflicts, you can place them in sub-folders inside the img folder, for instance, if you have images that should be displayed on the display.html file, place them in "public/img/display" that will make the work clean and leave no room for errors and image naming conflicts.
Please take your time to work on the changes, otherwise, you've done an impressive job, keep it up.

2021-11-13 19:12 UTC, Linusmugera commented
Noted with thanks



On Sat, Nov 13, 2021 at 9:01 PM Chalie Wizz ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Kindly follow the folder structure, firebase won't detect anything outside
> the public folder.
> Place all your images inside "public/img" and maybe you can create sub
> folders in there according to the respective HTML files where the images
> are to be displayed,
> do the same for the css files, place all your CSS files inside
> "public/css".
>
> Make sure you also check on the naming convention, if a css file belongs
> to display.html, it should be named display.css, the same case applies to
> js if you'll use an external file.
> If a js file belongs to display.html, name it display.js and place it
> inside the "pu
> blic/js" folder.
>
> For the images, to avoid name conflicts, you can place them in sub-folders
> inside the img folder, for instance, if you have images that should be
> displayed on the display.html file, place them in "public/img/display" that
> will make the work clean and leave no room for errors and image naming
> conflicts.
> Please take your time to work on the changes, otherwise, you've done an
> impressive job, keep it up.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/teau-ict-club/club-website/pull/23#pullrequestreview-805390428>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AL7PZ5PHFSRCSF6L4C5NEIDUL2RX7ANCNFSM5H3LPYZQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2022-02-17 07:26 UTC, Chal13W1zz approved these changes

2022-08-16 07:21 UTC, merged